# Generated by Django 5.0.7 on 2024-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=254, verbose_name="Заголовок"),
                ),
                ("ad_id", models.IntegerField(unique=True)),
                (
                    "author",
                    models.CharField(max_length=254, verbose_name="Автор"),
                ),
                (
                    "views",
                    models.IntegerField(verbose_name="Количество просмотров."),
                ),
                ("position", models.IntegerField(verbose_name="Позиция.")),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-views"],
            },
        ),
    ]
